# Generated by Django 4.1.4 on 2023-01-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='poststag', to='m2m.tag'),
        ),
    ]
